### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by gkucmierz** [narsenico/a-color-picker#59]
I am trying to add touch events, but is is not building on my side:

```
yarn run build
yarn run v1.22.18
warning ../package.json: No license field
$ webpack --config webpack.prod.js
clean-webpack-plugin: /Users/gkucmierz/workspace/a-color-picker/dist has been removed.
Hash: a6b6910bcf3ee9288238
Version: webpack 4.47.0
Time: 1391ms
Built at: 11/20/2023 10:24:28 PM
 1 asset
Entrypoint acolorpicker = acolorpicker.js
[1] ./src/acolorpicker.js 57.9 KiB {0} [built]
[2] ./src/utils.js 24.4 KiB {0} [built]
[4] ./src/acolorpicker.html 1.67 KiB {0} [built]
[5] ./src/acolorpicker.css 351 bytes {0} [built]
[6] ./node_modules/css-loader??ref--4-1!./src/acolorpicker.css 3.32 KiB {0} [built]
    + 3 hidden modules

WARNING in acolorpicker.js contains invalid source map

ERROR in acolorpicker.js from Terser
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:133:10)
    at /Users/gkucmierz/workspace/a-color-picker/node_modules/terser-webpack-plugin/dist/index.js:217:37
    at Array.forEach (<anonymous>)
    at TerserPlugin.optimizeFn (/Users/gkucmierz/workspace/a-color-picker/node_modules/terser-webpack-plugin/dist/index.js:160:259)
    at _next1 (eval at create (/Users/gkucmierz/workspace/a-color-picker/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:8:1)
    at eval (eval at create (/Users/gkucmierz/workspace/a-color-picker/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:30:1)
    at /Users/gkucmierz/workspace/a-color-picker/node_modules/uglifyjs-webpack-plugin/dist/index.js:287:11
    at step (/Users/gkucmierz/workspace/a-color-picker/node_modules/uglifyjs-webpack-plugin/dist/uglify/Runner.js:94:11)
    at done (/Users/gkucmierz/workspace/a-color-picker/node_modules/uglifyjs-webpack-plugin/dist/uglify/Runner.js:103:22)
    at /Users/gkucmierz/workspace/a-color-picker/node_modules/uglifyjs-webpack-plugin/dist/uglify/Runner.js:109:15
    at Runner.boundWorkers (/Users/gkucmierz/workspace/a-color-picker/node_modules/uglifyjs-webpack-plugin/dist/uglify/Runner.js:80:13)
    at enqueue (/Users/gkucmierz/workspace/a-color-picker/node_modules/uglifyjs-webpack-plugin/dist/uglify/Runner.js:100:17)
    at /Users/gkucmierz/workspace/a-color-picker/node_modules/uglifyjs-webpack-plugin/dist/uglify/Runner.js:120:11
    at Array.forEach (<anonymous>)
    at Runner.runTasks (/Users/gkucmierz/workspace/a-color-picker/node_modules/uglifyjs-webpack-plugin/dist/uglify/Runner.js:98:13)
    at UglifyJsPlugin.optimizeFn (/Users/gkucmierz/workspace/a-color-picker/node_modules/uglifyjs-webpack-plugin/dist/index.js:198:16)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/gkucmierz/workspace/a-color-picker/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:26:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/gkucmierz/workspace/a-color-picker/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/gkucmierz/workspace/a-color-picker/node_modules/webpack/lib/Compilation.js:1409:36
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/gkucmierz/workspace/a-color-picker/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/gkucmierz/workspace/a-color-picker/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/gkucmierz/workspace/a-color-picker/node_modules/webpack/lib/Compilation.js:1405:32
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/gkucmierz/workspace/a-color-picker/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/gkucmierz/workspace/a-color-picker/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.seal (/Users/gkucmierz/workspace/a-color-picker/node_modules/webpack/lib/Compilation.js:1342:27)
    at /Users/gkucmierz/workspace/a-color-picker/node_modules/webpack/lib/Compiler.js:675:18
    at /Users/gkucmierz/workspace/a-color-picker/node_modules/webpack/lib/Compilation.js:1261:4
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/gkucmierz/workspace/a-color-picker/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/gkucmierz/workspace/a-color-picker/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.finish (/Users/gkucmierz/workspace/a-color-picker/node_modules/webpack/lib/Compilation.js:1253:28)
    at /Users/gkucmierz/workspace/a-color-picker/node_modules/webpack/lib/Compiler.js:672:17
    at eval (eval at create (/Users/gkucmierz/workspace/a-color-picker/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
    at /Users/gkucmierz/workspace/a-color-picker/node_modules/webpack/lib/Compilation.js:1185:12
    at /Users/gkucmierz/workspace/a-color-picker/node_modules/webpack/lib/Compilation.js:1097:9
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by gkucmierz** [comment]
Actually `build:dev` is working fine.
